#!/bin/bash

# Check for user privileges
user=$(whoami)
if [ $user != root ];
then
echo User needs root privileges
echo try "\"sudo ./dep_install\""
exit
else
echo Good man, you are root
fi

echo "Installing development packages to compile dependencies..."

# Install all dependencies
apt-get install gcc
apt-get install automake
apt-get install autoconf
apt-get install 'make'
apt-get install -f "libopencv-*"
apt-get install scilab-sivp

cd dependencies
PRESENT_DIR=`pwd`

# Copying missing opencv headers
cp "include.tar" "/usr/include/"
cd /
tar -xvf "/usr/include/include.tar"
rm -r "/usr/include/include.tar"

# Installing scilab-IPD from dependencies folder
cd $PRESENT_DIR
ls $PRESENT_DIR
unzip -K IPD-8.3.1-1-src_patched.zip
echo "Unzipped files"
cd IPD/
#Running builder.sce which will compile the module
scilab-cli -f "builder.sce" -nb

# deleting folders..
cd $PRESENT_DIR
echo "deleting unzipped files and folder"
cd ..
rm -rf IPD/
echo "Installed IPD Successfully IN..."
echo "$PRESENT_DIR/IPD"
echo "Adding loader.sce path to Scilab"
echo "exec $PRESENT_DIR/IPD/etc/IPD.start; clc" >> /usr/share/scilab/contrib/loader.sce
echo "IPD installed..."
